### ISSUE TITLE
Server crash when using radio

### ISSUE THREAD

**Issue by thrca** [CodinGlitch/SimpleRadio#2]
As soon as the radio is right clicked, the server crashes.

Looks like the server is requesting a function that doesn't exist?

---snip
[21:16:05] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'de.maxhenkel.voicechat.voice.server.GroupManager de.maxhenkel.voicechat.voice.server.Server.getGroupManager()'
        at codinglit.ch.simpleradio.registry.RadioItem.transmit(RadioItem.java:37) ~[simpleradio-1.0.1.jar:?]
        at codinglit.ch.simpleradio.registry.RadioItem.method_7836(RadioItem.java:65) ~[simpleradio-1.0.1.jar:?]
        at net.minecraft.class_1799.method_7913(class_1799.java:276) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14256(class_3225.java:290) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12065(class_3244.java:1182) ~[server-intermediary.jar:?]
        at net.minecraft.class_2886.method_12550(class_2886.java:29) ~[server-intermediary.jar:?]
        at net.minecraft.class_2886.method_11054(class_2886.java:7) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by thrca** [comment]
Looks like the import from Simple Voice Chat should be "de.maxhenkel.voicechat.voice.server.ServerGroupManager" rather than "de.maxhenkel.voicechat.voice.server.GroupManager"

**Comment by thrca** [comment]
Max renamed GroupManager to ServerGroupManager in this commit... [https://github.com/henkelmax/simple-voice-chat/commit/c230d870c559cce0d3be03ae3130ced6b544319f](url)

**Comment by CodinGlitch** [comment]
Is this the 1.18.2 or the 1.19.2 version?

**Comment by thrca** [comment]
1.19.2 version. Using SVC 2.4.7. I looked at the source code for SVC.  It looks like in February (2.4.0) he renamed GroupManager to ServerGroupManager, and also he replaced open_groups with force_group_type=OPEN, discussed here: [https://github.com/henkelmax/simple-voice-chat/issues/560](url)

**Comment by CodinGlitch** [comment]
Yeah that's probably it. The radio was originally made for 2.3.3, and I haven't updated it much since. You could probably just use that version for now, and I'll get to updating the radio soon.

**Comment by CodinGlitch** [comment]
Should be fixed with the release of 1.0.2
