### ISSUE TITLE
Server crashes due to entrypoint Main

### ISSUE THREAD

**Issue by ABSOLUTEMAX123** [CodinGlitch/SimpleRadio#25]
[18:57:22] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'simpleradio'!
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66) ~[quilt-loader-0.25.0.jar:?]
        at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34) ~[quilt-loader-0.25.0.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64) ~[quilt-loader-0.25.0.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.25.0.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.25.0.jar:?]
        at org.quiltmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:65) ~[quilt-loader-0.25.0.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[minecraft-1.20.1.i0:0/:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) ~[quilt-loader-0.25.0.jar:?]
        at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) ~[quilt-loader-0.25.0.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) ~[quilt-loader-0.25.0.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:66) ~[quilt-loader-0.25.0.jar:?]
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Table with path [transceiver] has been declared twice.
        at com.electronwill.nightconfig.toml.TomlParser.checkContainsOnlySubtables(TomlParser.java:156) ~[com-electronwill-night-config-toml-3.6.6.i0:0/:?]
        at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:108) ~[com-electronwill-night-config-toml-3.6.6.i0:0/:?]
        at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:52) ~[com-electronwill-night-config-toml-3.6.6.i0:0/:?]
        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[com-electronwill-night-config-core-3.6.6.i0:0/:?]
        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[com-electronwill-night-config-core-3.6.6.i0:0/:?]
        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[com-electronwill-night-config-core-3.6.6.i0:0/:?]
        at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.load(WriteAsyncFileConfig.java:138) ~[com-electronwill-night-config-core-3.6.6.i0:0/:?]
        at com.codinglitch.simpleradio.lexiconfig.classes.LexiconData.load(LexiconData.java:71) ~[simpleradio-2.2.4.i0:0/:2.2.4]
        at com.codinglitch.simpleradio.lexiconfig.Lexiconfig.register(Lexiconfig.java:23) ~[simpleradio-2.2.4.i0:0/:2.2.4]
        at com.codinglitch.simpleradio.CommonSimpleRadio.initialize(CommonSimpleRadio.java:47) ~[simpleradio-2.2.4.i0:0/:2.2.4]
        at com.codinglitch.simpleradio.SimpleRadio.onInitialize(SimpleRadio.java:20) ~[simpleradio-2.2.4.i0:0/:2.2.4]
        at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:65) ~[quilt-loader-0.25.0.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.25.0.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.25.0.jar:?]
        ... 12 more

**Comment by ABSOLUTEMAX123** [comment]
further research finds that there is a duplicate table for the transciever

**Comment by CodinGlitch** [comment]
this _could_ be an issue with quilt, i haven't done any testing on it so i'm not sure how it performs on there. it's definitely an issue with the configuration though for some reason

**Comment by CodinGlitch** [comment]
stale
