### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Aabaddon** [CodinGlitch/SimpleRadio#3]
each time i try to use the radio it just instantly crashes

java.lang.NoSuchMethodError: 'de.maxhenkel.voicechat.voice.server.GroupManager de.maxhenkel.voicechat.voice.server.Server.getGroupManager()'
	at codinglit.ch.simpleradio.registry.RadioItem.transmit(RadioItem.java:37)
	at codinglit.ch.simpleradio.registry.RadioItem.method_7836(RadioItem.java:65)
	at net.minecraft.class_1799.method_7913(class_1799.java:276)
	at net.minecraft.class_3225.method_14256(class_3225.java:290)
	at net.minecraft.class_3244.method_12065(class_3244.java:1182)
	at net.minecraft.class_3244.onPlayerInteractItemParry(class_3244.java:4035)
	at net.minecraft.class_2886.redirect$dhm000$frycparry$injected(class_2886.java:517)
	at net.minecraft.class_2886.method_12550(class_2886.java:29)
	at net.minecraft.class_2886.method_11054(class_2886.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

the version of minecraft is 1.19.2 fabric 0.14.21

the version of simple voice radio is 1.0.1

the version of simple voice chat is 2.4.11

i have voice chat interaction in the version 1.0.3

**Comment by thrca** [comment]
This was resolved a few weeks ago... https://github.com/CodinGlitch/SimpleRadio/issues/2 
Try updating radio plugin to 1.0.2.

**Comment by Aabaddon** [comment]
oh...mb im just dumb, sorry sorry, the new place to download the mods is a bit confusing for me
