### ISSUE TITLE
[Critical Bug / Crash] Radios in player's inventory causes Player Ticking Error when joining a Multiplayer Server

### ISSUE THREAD

**Issue by archonxgames** [CodinGlitch/SimpleRadio#49]
**Issue:**
Player Ticking Error when joining a Multiplayer server on the latest update of Simple Radio. This was right after the server updated to the latest version of the mod 2.4.6.1 from the previous version.

**To Reproduce**
1. Have a radio from the previous update in your inventory.
2. Join the server after the latest version of the mod is installed.

**Version and Mod Loader:**
- Minecraft Version: 1.20.1
- Simple Radio Version: 2.4.6.1
- Mod Loader: Forge - 47.3.1

**Error Stacktrace:**
`net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:530) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.pattern" is null
	at java.util.regex.Pattern.<init>(Pattern.java:1428) ~[?:?]
	at java.util.regex.Pattern.compile(Pattern.java:1069) ~[?:?]
	at java.util.regex.Pattern.matches(Pattern.java:1174) ~[?:?]
	at java.lang.String.matches(String.java:2844) ~[?:?]
	at com.codinglitch.simpleradio.core.central.Frequency.check(Frequency.java:91) ~[SimpleRadio-forge-1.20.1-2.4.6.1.jar%23433!/:2.4.6.1]
	at com.codinglitch.simpleradio.core.registry.items.TransceiverItem.m_6883_(TransceiverItem.java:102) ~[SimpleRadio-forge-1.20.1-2.4.6.1.jar%23433!/:2.4.6.1]
	at net.minecraft.world.item.ItemStack.m_41666_(ItemStack.java:481) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	at net.minecraftforge.common.extensions.IForgeItem.onInventoryTick(IForgeItem.java:353) ~[forge-1.20.1-47.3.1-universal.jar%23474!/:?]
	at net.minecraftforge.common.extensions.IForgeItemStack.onInventoryTick(IForgeItemStack.java:306) ~[forge-1.20.1-47.3.1-universal.jar%23474!/:?]
	at net.minecraft.world.entity.player.Inventory.m_36068_(Inventory.java:230) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:499) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:241) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[server-1.20.1-20230612.114412-srg.jar%23469!/:?]
	... 9 more`

**Comment by archonxgames** [comment]
Same error also occurs when attempting to access the radiosmithing station

**Comment by CodinGlitch** [comment]
this looks like lexiconfig somehow didn't load the config, which definitely shouldn't be happening

**Comment by MCChiter** [comment]
Having the similar issue, didn't need previous version, we take fresh stuff from creative inventory and after trying to set frequency it ticks like crazy
forge 47.3.0 
server core arclight but we had same issue on Mohist
i tested it in SSP and holding shift shows it on-offs the current user rapidly. that may be the reason for ticking entity crash

**Comment by ziggytron** [comment]
having the same issue here
1.20.1 forge 47.4.0

**Comment by CodinGlitch** [comment]
should be fixed with SR3
